### PR TITLE
Add delay to RatesService startup (fixes #12760)

### PR DESCRIPTION
**Pull request by PrinceOfEgypt**
this is to address #1276 - I noticed that adding a startup delay to the ratesService caused to problem to go away, which leads me to believe that is some sort of concurrency issue. Please review as Java is not my primary language - there may be a better / more "correct" way to address the issue

### CODE REVIEW

**Comment by craigraw** [comment]
Interesting - haven't had a chance to look into this yet. Is there a reason to make the delay 5 seconds rather than 2?

**Comment by PrinceOfEgypt** [comment]
I tested it on windows, Mac, and Linux:

- The Mac would never manifest the issue even with no delay
- Ubuntu 23.04 worked every time with the 2 second delay
- Windows 10 still had the error once even with the 2 second delay, but could not reproduce the issue when I increased it to 5

**Comment by craigraw** [comment]
Interesting - typical of Windows to be worst. I'd prefer to get the request out sooner than 5 seconds if possible. What about 
```
ratesService.setDelay(Duration.seconds(org.controlsfx.tools.Platform.getCurrent() == org.controlsfx.tools.Platform.WINDOWS ? 5 : 2));
```

(with appropriate constants named and declared as you have done)

**Comment by PrinceOfEgypt** [comment]
Ok, in the interest of clarity I added a switch statement with a default value:

```
        switch(org.controlsfx.tools.Platform.getCurrent())
        {
            case WINDOWS:
                //Windows needs more time (5 Seconds)
                ratesService.setDelay(Duration.seconds(RATES_STARTUP_DELAY_SECS_WINDOWS));
                break;
            case OSX:
            case UNIX:
            case UNKNOWN:
            default:
                //Other platforms seem ok with 2 Seconds
                ratesService.setDelay(Duration.seconds(RATES_STARTUP_DELAY_SECS_DEFAULT));
                break;
        }
```

**Comment by craigraw** [comment]
Thanks, appreciate the cross-platform testing on this!

**Comment by craigraw** [comment]
I have edited it a bit for brevity. I'm a fan of keeping things terse :) Appreciate the work nonetheless.

**Comment by PrinceOfEgypt** [comment]
> I have edited it a bit for brevity. I'm a fan of keeping things terse :) Appreciate the work nonetheless.

No worries.. everyone had their own style :)

**Pull request merged**
